---
name: Nextcloud - MariaDB - Install - Firefox
author: Arne Tarara <arne@green-coding.io>
description: Installieren des offiziellen Nextcloud Docker containers mit MariaDB Datenbank. Dann booten und 1 Std. Idle.
compose-file: !include compose.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v14
#    depends_on:
#      nc:
#        condition: service_healthy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode
    setup-commands:
      - command: pip install dotenv


flow:
  - name: Install Nextcloud
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_install_done.py firefox

  # - name: Install Apps
  #   container: app
  #   commands:
  #     - type: console
  #       command: sudo -u www-data git clone --depth 1 -b stable32 https://github.com/nextcloud/text.git /var/www/html/apps/text/ && sudo -u www-data php /var/www/html/occ app:enable text
  #       shell: bash
  #     - type: console
  #       command: sudo -u www-data git clone --depth 1 -b stable32 https://github.com/nextcloud/calendar.git /var/www/html/apps/calendar/ && sudo -u www-data php /var/www/html/occ app:enable calendar
  #       shell: bash
  #     - type: console
  #       command: sudo -u www-data git clone --depth 1 -b stable32 https://github.com/nextcloud/contacts.git /var/www/html/apps/contacts/ && sudo -u www-data php /var/www/html/occ app:enable contacts
  #       shell: bash
  #     - type: console
  #       command: sudo -u www-data git clone --depth 1 -b stable32 https://github.com/nextcloud/spreed.git /var/www/html/apps/spreed/ && sudo -u www-data php /var/www/html/occ app:enable spreed
  #       shell: bash



  - name: Calendar
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_calendar_done.py firefox
        note: Creating event

  - name: Contacts
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_contacts_done.py firefox
        note: Creating event

  - name: Create User
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_docs_create_user_done.py firefox
        note: Creating event


  # - name: Docs create and share
  #   container: gcb-playwright
  #   commands:
  #     - type: console
  #       command: python3 /tmp/repo/stable32/nextcloud_docs_create_doc_and_share_done.py firefox
  #       note: Creating event

  - name: Files
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_files_done.py firefox
        note: Creating event

  - name: Talk
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/stable32/nextcloud_talk_done.py firefox
        note: Creating event
